#
# This file contains configuration flags to customize your site
#

# Site locale
lang: "en"

# Name of your site (displayed in the header)
title: Logan Hughes

# Short bio or description (displayed in the header)
description: Video Game SFX Artist

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: 

#
# Flags below are optional
#

# Your website URL (e.g. https://forever-jekyll.github.io or https://forever-jekyll.com)
# Used for Sitemap.xml and your RSS feed
url: https://loganhughesr.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Navigation menu
navigation_links:
  - title: Game Audio
    url: /
  - title: Instruments
    url: /instruments
  - title: Bio
    url: /bio

# Footer icons
footer_links:
  - title: Twitter
    url: https://twitter.com/lhughesaudio
    icon: fa fa-twitter
  - title: LinkedIn
    url: https://www.linkedin.com/in/logan-hughes-722958160
    icon: fa fa-linkedin

# Enter your copyright text if you wish to override the default one.
# copyright: "This site is made with <3 by *me, myself, and I*."

# Time zone
timezone: null

# Excerpt separator
excerpt_separator: <!--more-->

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: pretty

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Pagination
paginate: 5
paginate_path: "/blog/page/:num/"

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - webrick
  - jekyll-github-metadata

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
